name = "dive-log"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dive-log"
database_id = "9f91f34c-597d-41ff-841e-3bf134c0d387"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "dive-log"
